<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

    <!DOCTYPE text [
        <!ELEMENT text (concepts, sentence+)>
            <!ATTLIST text id CDATA #REQUIRED>
        <!ELEMENT concepts (concept+)>
            <!ELEMENT concept (#PCDATA)>
                <!ATTLIST concept id ID #REQUIRED>
        <!ELEMENT sentence (str, theme, rheme, semantic_roles)>
            <!ELEMENT str (#PCDATA)>
            <!ELEMENT theme (token*)>
                <!ATTLIST theme concept_ref IDREF #IMPLIED>
            <!ELEMENT rheme (token|mention)*>
                <!ATTLIST rheme concept_ref1 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref2 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref3 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref4 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref5 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref6 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref7 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref8 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref9 IDREF #IMPLIED>
                <!ATTLIST rheme concept_ref10 IDREF #IMPLIED>
            <!ELEMENT token (#PCDATA)>
                <!ATTLIST token pos CDATA #REQUIRED>
            <!ELEMENT mention (token+)>
                <!ATTLIST mention concept_ref CDATA #REQUIRED>
    		<!ELEMENT semantic_roles (frame|main_frame)*>
    		<!ELEMENT frame (argument*)>
                <!ATTLIST frame type CDATA #REQUIRED>
                <!ATTLIST frame head CDATA #REQUIRED>
    		<!ELEMENT main_frame (argument*)>
                <!ATTLIST main_frame type CDATA #REQUIRED>
                <!ATTLIST main_frame head CDATA #REQUIRED>
            <!ELEMENT argument EMPTY>
                <!ATTLIST argument type CDATA #REQUIRED>
                <!ATTLIST argument dependent CDATA #REQUIRED>
    ]>


    <text id="45_20000802_ssd">


	<concepts>
		<concept id="c_0">Las dos turistas alemanas que el pasado jueves se lanzaron de una furgoneta en marcha , una de las cuales murió al impactar con el asfalto ,</concept>
		<concept id="c_1">Sandra S. , de 24 años , que resultó herida al arrojarse detrás de su compañera Tanja Z. , de 25 años ,</concept>
		<concept id="c_2">el vehículo</concept>
		<concept id="c_3">las dos jóvenes</concept>
		<concept id="c_4">El conductor</concept>
		<concept id="c_5">el conductor</concept>
		<concept id="c_6">les</concept>
		<concept id="c_7">que el vehículo no iba excesivamente rápido</concept>
		<concept id="c_8">para</concept>
	</concepts>

	<sentence>
		<str>			
			 Las dos turistas alemanas que el pasado jueves se lanzaron de una furgoneta en marcha, una de las cuales murió al impactar con el asfalto, subieron al vehículo pensando que era un microbús que las llevaría desde La Zubia, donde se alojaban en un camping, hasta Granada, donde iban a visitar la Alhambra.
		</str>
		<theme concept_ref="c_0">
			<token pos="da0fp0">Las</token><token pos="dn0cp0">dos</token><token pos="nccp000">turistas</token><token pos="aq0fp0">alemanas</token><token pos="pr0cn000">que</token><token pos="da0ms0">el</token><token pos="aq0msp">pasado</token><token pos="ncms000">jueves</token><token pos="p0300000">se</token><token pos="vmis3p0">lanzaron</token><token pos="sps00">de</token><token pos="di0fs0">una</token><token pos="ncfs000">furgoneta</token><token pos="sps00">en</token><token pos="ncfs000">marcha</token><token pos="fc">,</token><token pos="pi0fs000">una</token><token pos="sps00">de</token><token pos="da0fp0">las</token><token pos="pr0cp000">cuales</token><token pos="vmis3s0">murió</token><token pos="spcms">al</token><token pos="vmn0000">impactar</token><token pos="sps00">con</token><token pos="da0ms0">el</token><token pos="ncms000">asfalto</token><token pos="fc">,</token>
		</theme>
		<rheme concept_ref1="c_4">
			<token pos="vmis3p0">subieron</token><token pos="vmg0000">pensando</token><token pos="cs">que</token><token pos="vsii3s0">era</token><mention concept_ref="c_4"><token pos="di0ms0">un</token><token pos="ncms000">microbús</token></mention>
		</rheme>
		<semantic_roles>
			<frame type="Arriving" head="visitar">
				<argument type="Theme" dependent="que las" />
				<argument type="Goal" dependent="la Alhambra" /></frame>
			<frame type="Calendric_unit" head="jueves" />
			<frame type="Cardinal_numbers" head="dos">
				<argument type="Entity" dependent="turistas alemanas" /></frame>
			<frame type="Cardinal_numbers" head="un">
				<argument type="Entity" dependent="que el" /></frame>
			<main_frame type="Death" head="murió">
				<argument type="Protagonist" dependent="una de las cuales" />
				<argument type="Containing_event" dependent="al impactar con el asfalto" /></main_frame>
			<frame type="Interior_profile_relation" head="en">
				<argument type="Figure" dependent="que las" />
				<argument type="Ground" dependent="un camping" /></frame>
			<frame type="Locative_relation" head="donde">
				<argument type="Figure" dependent="iban a visitar la Alhambra" /></frame>
			<main_frame type="Objective_influence" head="impactar">
				<argument type="Dependent_entity" dependent="con el asfalto" /></main_frame>
			<main_frame type="Opinion" head="pensando">
				<argument type="Opinion" dependent="era un microbús que las llevaría desde La Zubia" /></main_frame>
			<frame type="Residence" head="se alojaban">
				<argument type="Location" dependent="donde" />
				<argument type="Resident" dependent="que las" />
				<argument type="Location" dependent="en un camping" /></frame>
			<main_frame type="Shoot_projectiles" head="lanzaron">
				<argument type="Agent" dependent="dos turistas alemanas que el" /></main_frame>
			<frame type="Taking_time" head="se">
				<argument type="Activity" dependent="un microbús que" />
				<argument type="Time_length" dependent="las" />
				<argument type="Activity" dependent="desde La Zubia , donde se alojaban en un camping , hasta Granada , donde iban a visitar la Alhambra" /></frame>
			<frame type="Temporal_collocation" head="se">
				<argument type="Trajector_event" dependent="dos turistas alemanas que el pasado jueves se lanzaron de una furgoneta en marcha" />
				<argument type="Trajector_event" dependent="una de las cuales murió al" />
				<argument type="Landmark_event" dependent="impactar con el asfalto" />
				<argument type="Trajector_event" dependent=", donde se alojaban en un camping , hasta Granada , donde iban a visitar la Alhambra" /></frame>
			<frame type="Vehicle" head="microbús" />
			<frame type="Vehicle" head="vehículo" />
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Sandra S., de 24 años, que resultó herida al arrojarse detrás de su compañera Tanja Z., de 25 años, declaró que subieron en los asientos traseros algo extrañadas porque el conductor no les cobraba el viaje.
		</str>
		<theme concept_ref="c_1">
			<token pos="np0000l">Sandra</token><token pos="np0000l">S.</token><token pos="fc">,</token><token pos="sps00">de</token><token pos="z">24</token><token pos="ncmp000">años</token><token pos="fc">,</token><token pos="pr0cn000">que</token><token pos="vmis3s0">resultó</token><token pos="aq0fsp">herida</token><token pos="spcms">al</token><token pos="vmn0000">arrojarse</token><token pos="rg">detrás</token><token pos="sps00">de</token><token pos="dp3cs0">su</token><token pos="ncfs000">compañera</token><token pos="np0000l">Tanja</token><token pos="np0000l">Z.</token><token pos="fc">,</token><token pos="sps00">de</token><token pos="z">25</token><token pos="ncmp000">años</token><token pos="fc">,</token>
		</theme>
		<rheme concept_ref1="c_3" concept_ref2="c_4" concept_ref3="c_5" concept_ref4="c_6">
			<token pos="vmis3p0">subieron</token><token pos="sps00">en</token><mention concept_ref="c_3"><token pos="da0mp0">los</token><token pos="ncmp000">asientos</token></mention><token pos="aq0mp0">traseros</token><token pos="rg">algo</token><token pos="aq0fpp">extrañadas</token><token pos="cs">porque</token><token pos="da0ms0">el</token><token pos="ncms000">conductor</token><token pos="rn">no</token><mention concept_ref="c_6"><token pos="pp3cpd00">les</token></mention><token pos="vmii3s0">cobraba</token><token pos="da0ms0">el</token><token pos="ncms000">viaje</token>
		</rheme>
		<semantic_roles>
			<frame type="Body_parts" head="traseros">
				<argument type="Possessor" dependent="les" /></frame>
			<frame type="Causation" head="porque">
				<argument type="Effect" dependent="subieron en los asientos traseros algo extrañadas" />
				<argument type="Cause" dependent="el conductor no les cobraba el" /></frame>
			<frame type="Degree" head="algo">
				<argument type="Gradable_attribute" dependent="extrañadas" /></frame>
			<main_frame type="Judgment_communication" head="cobraba el">
				<argument type="Communicator" dependent="el conductor" />
				<argument type="Evaluee" dependent="les" /></main_frame>
			<frame type="Ride_vehicle" head="viaje">
				<argument type="Vehicle" dependent="les" /></frame>
			<frame type="Statement" head="declaró">
				<argument type="Speaker" dependent="que resultó herida al arrojarse detrás de su compañera Tanja Z. , de 25 años" />
				<argument type="Message" dependent="que subieron en los asientos traseros algo extrañadas porque el conductor no les cobraba el viaje" /></frame>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Cuando el vehículo sobrepasó la capital granadina, las dos turistas comenzaron a inquietarse y, cuando pidieron explicaciones al conductor, éste, como respuesta, intentó tocarles las piernas.
		</str>
		<theme concept_ref="c_2">
			<token pos="da0ms0">el</token><token pos="ncms000">vehículo</token>
		</theme>
		<rheme>
			<token pos="vmis3s0">sobrepasó</token><token pos="da0fs0">la</token><token pos="ncfs000">capital</token><token pos="aq0fs0">granadina</token>
		</rheme>
		<semantic_roles>
			<frame type="Activity_start" head="comenzaron">
				<argument type="Time" dependent="Cuando el vehículo sobrepasó la capital granadina" />
				<argument type="Agent" dependent="las dos turistas" />
				<argument type="Activity" dependent="a inquietarse" /></frame>
			<frame type="Attempt" head="intentó">
				<argument type="Goal" dependent="tocarles las piernas" /></frame>
			<frame type="Cardinal_numbers" head="dos">
				<argument type="Entity" dependent="turistas" /></frame>
			<frame type="Getting" head="las">
				<argument type="Recipient" dependent="las dos turistas" />
				<argument type="Theme" dependent="sobrepasó" /></frame>
			<frame type="Questioning" head="respuesta">
				<argument type="Speaker" dependent="pidieron" />
				<argument type="Message" dependent="explicaciones al conductor , éste , como respuesta ," /></frame>
			<frame type="Relational_political_locales" head="capital">
				<argument type="Name" dependent="granadina" /></frame>
			<frame type="Response" head="respuesta" />
			<frame type="Vehicle" head="vehículo" />
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Tras varios forcejeos y gritos de auxilio por la ventana, y presas del miedo, las dos jóvenes saltaron en marcha pensando que el vehículo no iba excesivamente rápido.
		</str>
		<theme concept_ref="c_3">
			<token pos="da0fp0">las</token><token pos="dn0cp0">dos</token><token pos="nccp000">jóvenes</token>
		</theme>
		<rheme concept_ref1="c_2" concept_ref2="c_7">
			<token pos="vmis3p0">saltaron</token><token pos="vmg0000">pensando</token><mention concept_ref="c_7"><token pos="cs">que</token><token pos="da0ms0">el</token><token pos="ncms000">vehículo</token><token pos="rn">no</token><token pos="vmii3s0">iba</token><token pos="rg">excesivamente</token><token pos="aq0ms0">rápido</token></mention>
		</rheme>
		<semantic_roles>
			<frame type="Age" head="jóvenes">
				<argument type="Entity" dependent="las" /></frame>
			<frame type="Assistance" head="auxilio">
				<argument type="Goal" dependent="por la ventana" /></frame>
			<frame type="Cardinal_numbers" head="dos">
				<argument type="Entity" dependent="jóvenes" /></frame>
			<frame type="Connecting_architecture" head="ventana" />
			<frame type="Fear" head="miedo" />
			<frame type="Hostile_encounter" head="forcejeos">
				<argument type="Sides" dependent="varios" /></frame>
			<frame type="Interior_profile_relation" head="en">
				<argument type="Ground" dependent="miedo" /></frame>
			<main_frame type="Opinion" head="pensando">
				<argument type="Cognizer" dependent="Tras" />
				<argument type="Opinion" dependent="que el vehículo no iba excesivamente rápido" /></main_frame>
			<frame type="People" head="las">
				<argument type="Descriptor" dependent="jóvenes" /></frame>
			<frame type="Quantified_mass" head="varios">
				<argument type="Individuals" dependent="forcejeos" /></frame>
			<frame type="Relative_time" head="por">
				<argument type="Landmark_occasion" dependent="varios forcejeos y gritos de auxilio por la ventana" />
				<argument type="Focal_occasion" dependent="excesivamente rápido" /></frame>
			<frame type="Roadways" head="Tras" />
			<frame type="Spatial_contact" head="en">
				<argument type="Figure" dependent="las dos jóvenes" />
				<argument type="Ground" dependent="Tras" /></frame>
			<frame type="Speed_description" head="rápido">
				<argument type="Entity" dependent="el vehículo" />
				<argument type="Degree" dependent="en" /></frame>
			<main_frame type="Traversing" head="saltaron">
				<argument type="Theme" dependent="las dos jóvenes" />
				<argument type="Place" dependent="en marcha" /></main_frame>
			<frame type="Vehicle" head="vehículo" />
			<frame type="Vocalizations" head="gritos" />
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 El conductor no paró para auxiliarlas.
		</str>
		<theme concept_ref="c_4">
			<token pos="da0ms0">El</token><token pos="ncms000">conductor</token>
		</theme>
		<rheme concept_ref1="c_8">
			<token pos="rn">no</token><token pos="vmis3s0">paró</token><mention concept_ref="c_8"><token pos="sps00">para</token></mention><token pos="vmn0000">auxiliarlas</token>
		</rheme>
		<semantic_roles>
			<main_frame type="Assistance" head="auxiliarlas">
				<argument type="Benefited_party" dependent="para" /></main_frame>
			<frame type="Preventing_or_letting" head="para">
				<argument type="Potential_hindrance" dependent="El conductor" />
				<argument type="Event" dependent="para auxiliarlas" /></frame>
		</semantic_roles>
	</sentence>
	
</text>