<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
    <!ELEMENT text (concepts, sentence+)>
        <!ATTLIST text id CDATA #REQUIRED>
    <!ELEMENT concepts (concept+)>
        <!ELEMENT concept (#PCDATA)>
            <!ATTLIST concept id ID #REQUIRED>
    <!ELEMENT sentence (theme, rheme, semantic_roles)>
        <!ELEMENT theme (token*)>
            <!ATTLIST theme concept_ref IDREF #IMPLIED>
        <!ELEMENT rheme (token|mention)*>
            <!ATTLIST rheme concept_ref1 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref2 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref3 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref4 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref5 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref6 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref7 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref8 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref9 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref10 IDREF #IMPLIED>
        <!ELEMENT token (#PCDATA)>
            <!ATTLIST token pos CDATA #REQUIRED>
        <!ELEMENT mention (token+)>
            <!ATTLIST mention concept_ref CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame|main_frame)*>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT main_frame (argument*)>
            <!ATTLIST main_frame type CDATA #REQUIRED>
            <!ATTLIST main_frame head CDATA #REQUIRED>
        <!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="10_20010402_a_ssd_annotated_recursive">


	<concepts>
		<concept id="c_0">Nadie que conozca las políticas y los problemas que aquejan al sector pesquero</concept>
		<concept id="c_1">el asombro</concept>
		<concept id="c_2">La lógica de los pescadores</concept>
		<concept id="c_3">El mar</concept>
		<concept id="c_4">el mar el pescado</concept>
		<concept id="c_5">el hombre la ley de la naturaleza</concept>
		<concept id="c_6">el mar su riqueza</concept>
		<concept id="c_7">sus argumentos , romos en jurídica y política ,</concept>
		<concept id="c_8">Ningún acuerdo</concept>
		<concept id="c_9">Marruecos España</concept>
		<concept id="c_10">nada de esto</concept>
		<concept id="c_11">Mucha gente</concept>
		<concept id="c_12">ellos</concept>
		<concept id="c_13">delirio</concept>
		<concept id="c_14">tuyo</concept>
		<concept id="c_15">sus aguas</concept>
	</concepts>

	<sentence>
		<theme concept_ref="c_0">
			<token pos="pi0cs000">Nadie</token><token pos="pr0cn000">que</token><token pos="vmsp3s0">conozca</token><token pos="da0fp0">las</token><token pos="ncfp000">políticas</token><token pos="cc">y</token><token pos="da0mp0">los</token><token pos="ncmp000">problemas</token><token pos="pr0cn000">que</token><token pos="vmip3p0">aquejan</token><token pos="spcms">al</token><token pos="ncms000">sector</token><token pos="aq0ms0">pesquero</token>
		</theme>
		<rheme>
			<token pos="vmip3s0">puede</token><token pos="vmn0000">mostrarse</token><token pos="aq0msp">sorprendido</token><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="ncfs000">actitud</token><token pos="aq0cs0">marroquí</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
			<frame type="Fields" head="sector" />
			<frame type="Fields" head="sector" />
			<frame type="Fields" head="sector" />
			<frame type="Fields" head="sector" />
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_1">
			<token pos="da0ms0">el</token><token pos="ncms000">asombro</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="aq0cs0">inevitable</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
			<frame type="Time_vector" head="ante">
				<argument type="Event" dependent="la necesidad de reducir unas flotas de pesca sobredimensionadas, con exceso de potencia, exceso de años y condiciones de seguridad bajo" /></frame>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme>
		</theme>
		<rheme>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_2">
			<token pos="da0fs0">La</token><token pos="ncfs000">lógica</token><token pos="sps00">de</token><token pos="da0mp0">los</token><token pos="ncmp000">pescadores</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="aq0cs0">irrefutable</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_3">
			<token pos="da0ms0">El</token><token pos="nccs000">mar</token>
		</theme>
		<rheme concept_ref1="c_6" concept_ref2="c_7" concept_ref3="c_12" concept_ref4="c_13">
			<token pos="fc">,</token><token pos="sps00">para</token><mention concept_ref="c_12"><token pos="pp3mp000">ellos</token></mention><token pos="fc">,</token><token pos="vsip3s0">es</token><mention concept_ref="c_6"><token pos="di0fs0">una</token><token pos="ncfs000">inmensidad</token></mention><token pos="aq0cs0">inabarcable</token><token pos="sps00">por</token><token pos="da0fs0">la</token><token pos="pr0cn000">que</token><token pos="vmip3s0">merodea</token><token pos="fc">,</token><token pos="aq0ms0">ajeno</token><token pos="spcms">al</token><mention concept_ref="c_13"><token pos="ncms000">delirio</token></mention><token pos="aq0ms0">macroeconómico</token><token pos="fc">,</token><mention concept_ref="c_7"><token pos="dp3cs0">su</token><token pos="aq0ms0">escurridizo</token><token pos="ncms000">sustento</token></mention><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_4">
			<token pos="da0ms0">el</token><token pos="nccs000">mar</token><token pos="da0ms0">el</token><token pos="ncms000">pescado</token>
		</theme>
		<rheme concept_ref1="c_9" concept_ref2="c_14">
			<token pos="vmip3s0">tiene</token><mention concept_ref="c_9"><token pos="di0mp0">varios</token><token pos="ncmp000">dueños</token></mention><token pos="rn">no</token><token pos="vsip3s0">es</token><mention concept_ref="c_14"><token pos="px2ms0s0">tuyo</token></mention>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_5">
			<token pos="da0ms0">el</token><token pos="ncms000">hombre</token><token pos="da0fs0">la</token><token pos="ncfs000">ley</token><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="ncfs000">naturaleza</token>
		</theme>
		<rheme concept_ref1="c_12">
			<token pos="fc">,</token><mention concept_ref="c_12"><token pos="da0ns0">lo</token></mention><token pos="pr0cn000">que</token><token pos="vmip3s0">ignora</token>
		</rheme>
		<semantic_roles>
			<frame type="Misdeed" head="sin" />
		</semantic_roles>
	</sentence>
	<sentence>
		<theme>
		</theme>
		<rheme>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_6">
			<token pos="da0ms0">el</token><token pos="nccs000">mar</token><token pos="dp3cs0">su</token><token pos="ncfs000">riqueza</token>
		</theme>
		<rheme>
			<token pos="rn">no</token><token pos="vsip3s0">es</token><token pos="aq0cs0">libre</token><token pos="p0300000">se</token><token pos="vmip3s0">agota</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_7">
			<token pos="dp3cp0">sus</token><token pos="ncmp000">argumentos</token><token pos="fc">,</token><token pos="aq0mp0">romos</token><token pos="sps00">en</token><token pos="aq0fs0">jurídica</token><token pos="cc">y</token><token pos="ncfs000">política</token><token pos="fc">,</token>
		</theme>
		<rheme concept_ref1="c_6">
			<token pos="rn">no</token><token pos="vmip3p0">presentan</token><mention concept_ref="c_6"><token pos="ncfp000">fisuras</token></mention><token pos="aq0cp0">morales</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_8">
			<token pos="di0ms0">Ningún</token><token pos="ncms000">acuerdo</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="aq0ms0">bueno</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_9">
			<token pos="np00000">Marruecos</token><token pos="np00000">España</token>
		</theme>
		<rheme concept_ref1="c_6" concept_ref2="c_9" concept_ref3="c_12" concept_ref4="c_15">
			<token pos="vmic3s0">debería</token><token pos="vmn0000">dejarnos</token><token pos="vmn0000">faenar</token><token pos="sps00">en</token><mention concept_ref="c_15"><token pos="dp3cp0">sus</token><token pos="ncfp000">aguas</token></mention><token pos="vmic3s0">debería</token><token pos="vmn0000">dejar</token><token pos="sps00">a</token><mention concept_ref="c_6"><token pos="da0mp0">los</token><token pos="nccp000">marroquís</token></mention><token pos="vmn0000">trabajar</token><token pos="sps00">en</token><token pos="ncfs000">paz</token><token pos="sps00">en</token><mention concept_ref="c_9"><token pos="dp1mpp">nuestros</token><token pos="ncmp000">campos</token></mention>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_10">
			<token pos="pi0cs000">nada</token><token pos="sps00">de</token><token pos="pd0ns000">esto</token>
		</theme>
		<rheme concept_ref1="c_11" concept_ref2="c_8" concept_ref3="c_6" concept_ref4="c_4" concept_ref5="c_3" concept_ref6="c_12" concept_ref7="c_13" concept_ref8="c_14" concept_ref9="c_15">
			<token pos="vmif3s0">pasará</token><token pos="sps00">hasta</token><token pos="cs">que</token><token pos="vmsp1p0">comprendamos</token><token pos="cs">que</token><mention concept_ref="c_11"><token pos="dp1fpp">nuestras</token><token pos="ncfp000">redes</token></mention><token pos="fg">-</token><token pos="fg">-</token><token pos="aq0fp0">telefónicas</token><token pos="fc">,</token><token pos="aq0fp0">informáticas</token><token pos="fc">,</token><token pos="aq0fp0">narcóticas</token><token pos="fg">-</token><token pos="fg">-</token><token pos="vsip3p0">son</token><token pos="rg">sólo</token><token pos="ncfp000">derivaciones</token><token pos="aq0fp0">inciertas</token><token pos="sps00">de</token><mention concept_ref="c_6"><token pos="pd0fp000">aquellas</token></mention><token pos="pr0cn000">que</token><mention concept_ref="c_4"><token pos="da0ms0">el</token><token pos="ncms000">hombre</token></mention><token pos="vmii3s0">usaba</token><token pos="sps00">para</token><token pos="vmn0000">vivir</token><token pos="cs">cuando</token><mention concept_ref="c_3"><token pos="da0ms0">el</token><token pos="nccs000">mar</token></mention><token pos="vsii3s0">era</token><mention concept_ref="c_14"><token pos="pi0ms000">uno</token></mention><token pos="cc">y</token><token pos="vmii3s0">daba</token><token pos="sps00">para</token><token pos="pi0mp000">todos</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
			<frame type="Calendric_unit" head="era" />
			<frame type="Calendric_unit" head="era" />
			<frame type="Calendric_unit" head="era" />
			<frame type="Calendric_unit" head="era" />
			<frame type="Calendric_unit" head="era" />
			<main_frame type="Calendric_unit" head="era" />
			<frame type="Calendric_unit" head="era" />
			<frame type="Kinship" head="son" />
			<frame type="Kinship" head="son" />
			<main_frame type="Kinship" head="son" />
			<frame type="Kinship" head="son" />
			<frame type="Kinship" head="son" />
			<frame type="Kinship" head="son" />
			<frame type="Kinship" head="son" />
		</semantic_roles>
	</sentence>
	<sentence>
		<theme>
		</theme>
		<rheme>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<theme concept_ref="c_11">
			<token pos="di0fs0">Mucha</token><token pos="ncfs000">gente</token>
		</theme>
		<rheme concept_ref1="c_1" concept_ref2="c_3" concept_ref3="c_12" concept_ref4="c_13" concept_ref5="c_15">
			<token pos="vmip3s0">quiere</token><token pos="vmn0000">seguir</token><token pos="vmg0000">viviendo</token><token pos="cs">como</token><token pos="cs">cuando</token><mention concept_ref="c_1"><token pos="da0mp0">los</token><token pos="ncmp000">océanos</token></mention><token pos="rn">no</token><token pos="vmii3p0">tenían</token><mention concept_ref="c_15"><token pos="ncmp000">amos</token></mention><token pos="cc">y</token><mention concept_ref="c_13"><token pos="da0ms0">el</token><token pos="ncms000">fruto</token></mention><token pos="sps00">de</token><mention concept_ref="c_3"><token pos="da0fs0">la</token><token pos="nccs000">mar</token></mention><token pos="vsii3s0">era</token><token pos="aq0ms0">infinito</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
			<frame type="Calendric_unit" head="era" />
			<frame type="Calendric_unit" head="era" />
			<frame type="Calendric_unit" head="era" />
			<frame type="Calendric_unit" head="era" />
			<main_frame type="Calendric_unit" head="era" />
		</semantic_roles>
	</sentence>
	
</text>