<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
    <!ELEMENT text (concepts, sentence+)>
        <!ATTLIST text id CDATA #REQUIRED>
    <!ELEMENT concepts (concept+)>
        <!ELEMENT concept (#PCDATA)>
            <!ATTLIST concept id ID #REQUIRED>
    <!ELEMENT sentence (str, theme, rheme, semantic_roles)>
        <!ELEMENT str (#PCDATA)>
        <!ELEMENT theme (token*)>
            <!ATTLIST theme concept_ref IDREF #IMPLIED>
        <!ELEMENT rheme (token|mention)*>
            <!ATTLIST rheme concept_ref1 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref2 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref3 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref4 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref5 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref6 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref7 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref8 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref9 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref10 IDREF #IMPLIED>
        <!ELEMENT token (#PCDATA)>
            <!ATTLIST token pos CDATA #REQUIRED>
        <!ELEMENT mention (token+)>
            <!ATTLIST mention concept_ref CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame|main_frame)*>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT main_frame (argument*)>
            <!ATTLIST main_frame type CDATA #REQUIRED>
            <!ATTLIST main_frame head CDATA #REQUIRED>
        <!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="3_19991202_ssd">


	<concepts>
		<concept id="c_0">La UE</concept>
		<concept id="c_1">Los Quince</concept>
		<concept id="c_2">Esta fórmula</concept>
		<concept id="c_3">La policía y la Guardia Nacional</concept>
		<concept id="c_4">El alcalde</concept>
		<concept id="c_5">Seattle</concept>
		<concept id="c_6">Cientos de policías pertrechados con material antidisturbio pesado</concept>
		<concept id="c_7">Muchos escaparates de las tiendas y de los centros comerciales</concept>
		<concept id="c_8">Las unidades policiales</concept>
		<concept id="c_9">El número de detenidos por los incidentes</concept>
		<concept id="c_10">grupos de jóvenes , algunos disfrazados de tortugas o de otros animales ,</concept>
		<concept id="c_11">Las fuerzas de seguridad</concept>
		<concept id="c_12">unos 200 miembros de la Guardia Nacional</concept>
		<concept id="c_13">La policía</concept>
		<concept id="c_14">Los incidentes del martes</concept>
		<concept id="c_15">Paul Schell , alcalde de Seattle ,</concept>
		<concept id="c_16">el toque de queda y el estado de emergencia</concept>
		<concept id="c_17">unos 2.000 manifestantes radicales</concept>
		<concept id="c_18">La policía , que tardó varias horas en controlar la situación ,</concept>
		<concept id="c_19">Clinton</concept>
		<concept id="c_20">trabajo</concept>
		<concept id="c_21">madrugada</concept>
		<concept id="c_22">España</concept>
		<concept id="c_23">se</concept>
		<concept id="c_24">la mañana</concept>
	</concepts>

	<sentence>
		<str>			
			 La UE aprovechó la referencia de Clinton a posibles sanciones comerciales por motivos laborales para ganar el apoyo de esos países.
		</str>
		<theme concept_ref="c_0">
			<token pos="da0fs0">La</token><token pos="np00000">UE</token>
		</theme>
		<rheme concept_ref1="c_5" concept_ref2="c_8" concept_ref3="c_19">
			<token pos="vmis3s0">aprovechó</token><mention concept_ref="c_5"><token pos="da0fs0">la</token><token pos="ncfs000">referencia</token></mention><token pos="sps00">de</token><mention concept_ref="c_19"><token pos="np00000">Clinton</token></mention><token pos="sps00">a</token><token pos="aq0cp0">posibles</token><mention concept_ref="c_8"><token pos="ncfp000">sanciones</token></mention><token pos="aq0cp0">comerciales</token><token pos="sps00">por</token><token pos="ncmp000">motivos</token><token pos="aq0cp0">laborales</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Los Quince sólo defienden crear un foro de trabajo permanente entre la OMC y la Organización Internacional de Trabajo para reforzar el respeto de los derechos laborales y excluye la posibilidad de sanciones.
		</str>
		<theme concept_ref="c_1">
			<token pos="da0mp0">Los</token><token pos="pn0cp000">Quince</token>
		</theme>
		<rheme concept_ref1="c_3" concept_ref2="c_5" concept_ref3="c_9" concept_ref4="c_20">
			<token pos="vmip3p0">defienden</token><token pos="vmn0000">crear</token><token pos="di0ms0">un</token><token pos="ncms000">foro</token><token pos="sps00">de</token><mention concept_ref="c_20"><token pos="ncms000">trabajo</token></mention><token pos="aq0cs0">permanente</token><token pos="sps00">entre</token><mention concept_ref="c_3"><token pos="da0fs0">la</token><token pos="np00000">OMC</token></mention><token pos="cc">y</token><token pos="da0fs0">la</token><token pos="ncms000">Organización</token><token pos="ncms000">Internacional</token><token pos="sps00">de</token><token pos="ncms000">Trabajo</token><token pos="sps00">para</token><token pos="vmn0000">reforzar</token><mention concept_ref="c_5"><token pos="da0ms0">el</token><token pos="ncms000">respeto</token></mention><token pos="sps00">de</token><mention concept_ref="c_9"><token pos="da0mp0">los</token><token pos="ncmp000">derechos</token></mention><token pos="aq0cp0">laborales</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Esta fórmula sería aceptable para los países en desarrollo, ya que no establece compromisos.
		</str>
		<theme concept_ref="c_2">
			<token pos="dd0fs0">Esta</token><token pos="ncfs000">fórmula</token>
		</theme>
		<rheme concept_ref1="c_8" concept_ref2="c_23">
			<token pos="vsic3s0">sería</token><token pos="aq0cs0">aceptable</token><token pos="sps00">para</token><mention concept_ref="c_8"><token pos="da0mp0">los</token><token pos="ncmp000">países</token></mention><token pos="sps00">en</token><token pos="ncms000">desarrollo</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 La policía y la Guardia Nacional impiden más concentraciones ante el centro de congresos.
		</str>
		<theme concept_ref="c_3">
			<token pos="da0fs0">La</token><token pos="nccs000">policía</token><token pos="cc">y</token><token pos="da0fs0">la</token><token pos="ncms000">Guardia</token><token pos="aq0ms0">Nacional</token>
		</theme>
		<rheme concept_ref1="c_1" concept_ref2="c_5" concept_ref3="c_14" concept_ref4="c_9" concept_ref5="c_19">
			<token pos="vmip3p0">impiden</token><token pos="rg">más</token><mention concept_ref="c_1"><token pos="ncfp000">concentraciones</token></mention><token pos="sps00">ante</token><token pos="da0ms0">el</token><mention concept_ref="c_9"><token pos="ncms000">centro</token></mention><token pos="sps00">de</token><mention concept_ref="c_14"><token pos="ncmp000">congresos</token></mention>
		</rheme>
		<semantic_roles>
			<frame type="Time_vector" head="ante">
				<argument type="Event" dependent="y la Guardia Nacional" />
				<argument type="Event" dependent="el centro de congresos" /></frame>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 El alcalde avisa de que evitará más incidentes violentos, que acabaron con 240 detenciones
		</str>
		<theme concept_ref="c_4">
			<token pos="da0ms0">El</token><token pos="ncms000">alcalde</token>
		</theme>
		<rheme concept_ref1="c_1">
			<token pos="vmip3s0">avisa</token><token pos="sps00">de</token><token pos="cs">que</token><token pos="vmif3s0">evitará</token><token pos="rg">más</token><mention concept_ref="c_1"><token pos="nccp000">incidentes</token></mention><token pos="aq0mp0">violentos</token><token pos="fc">,</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Seattle amaneció ayer bajo un estricto control policial, tras los violentos incidentes protagonizados en la tarde y la noche del Martes ( madrugada de ayer en España ) por diversos grupos radicales que lograron bloquear la apertura de la conferencia ministerial de la Organización Mundial de Comercio ( OMC ).
		</str>
		<theme concept_ref="c_5">
			<token pos="np00000">Seattle</token>
		</theme>
		<rheme concept_ref1="c_1" concept_ref2="c_9" concept_ref3="c_14" concept_ref4="c_4" concept_ref5="c_10" concept_ref6="c_5" concept_ref7="c_19" concept_ref8="c_20" concept_ref9="c_21" concept_ref10="c_22">
			<token pos="vmis3s0">amaneció</token><token pos="sps00">bajo</token><mention concept_ref="c_9"><token pos="di0ms0">un</token><token pos="aq0ms0">estricto</token><token pos="ncms000">control</token></mention><token pos="aq0cs0">policial</token><token pos="sps00">tras</token><token pos="da0mp0">los</token><token pos="aq0mp0">violentos</token><mention concept_ref="c_1"><token pos="nccp000">incidentes</token></mention><token pos="aq0mpp">protagonizados</token><token pos="sps00">en</token><mention concept_ref="c_20"><token pos="da0fs0">la</token><token pos="ncfs000">tarde</token></mention><token pos="cc">y</token><mention concept_ref="c_4"><token pos="da0fs0">la</token><token pos="ncfs000">noche</token></mention><token pos="spcms">del</token><token pos="ncms000">Martes</token><token pos="fpa">(</token><mention concept_ref="c_21"><token pos="ncfs000">madrugada</token></mention><token pos="sps00">de</token><token pos="rg">ayer</token><token pos="sps00">en</token><mention concept_ref="c_22"><token pos="np00000">España</token></mention><token pos="fpt">)</token><token pos="sps00">por</token><mention concept_ref="c_10"><token pos="di0mp0">diversos</token><token pos="ncmp000">grupos</token></mention><token pos="aq0cp0">radicales</token>
		</rheme>
		<semantic_roles>
			<frame type="Being_in_control" head="control">
				<argument type="Controlling_entity" dependent="amaneció ayer bajo un" />
				<argument type="Dependent_entity" dependent="de" /></frame>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Cientos de policías pertrechados con material antidisturbio pesado controlaron las calles del centro de la ciudad, en especial un amplio perímetro alrededor del centro de congresos.
		</str>
		<theme concept_ref="c_6">
			<token pos="pn0cp000">Cientos</token><token pos="sps00">de</token><token pos="nccp000">policías</token><token pos="aq0mpp">pertrechados</token><token pos="sps00">con</token><token pos="ncms000">material</token><token pos="aq0cs0">antidisturbio</token><token pos="aq0ms0">pesado</token>
		</theme>
		<rheme concept_ref1="c_5" concept_ref2="c_14" concept_ref3="c_8" concept_ref4="c_9" concept_ref5="c_13" concept_ref6="c_6" concept_ref7="c_19" concept_ref8="c_20" concept_ref9="c_22" concept_ref10="c_21">
			<token pos="vmis3p0">controlaron</token><token pos="da0fp0">las</token><token pos="ncfp000">calles</token><token pos="spcms">del</token><token pos="ncms000">centro</token><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="ncfs000">ciudad</token><token pos="sps00">en</token><token pos="aq0msp">especial</token><mention concept_ref="c_6"><token pos="di0ms0">un</token><token pos="aq0ms0">amplio</token><token pos="ncms000">perímetro</token></mention><token pos="rg">alrededor</token><token pos="spcms">del</token><token pos="ncms000">centro</token><token pos="sps00">de</token><mention concept_ref="c_14"><token pos="ncmp000">congresos</token></mention>
		</rheme>
		<semantic_roles>
			<frame type="Ingredients" head="material">
				<argument type="Descriptor" dependent="pertrechados con" /></frame>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Muchos escaparates de las tiendas y de los centros comerciales fueron tapados con planchas de madera tras la ruptura de sus lunas la víspera.
		</str>
		<theme concept_ref="c_7">
			<token pos="di0mp0">Muchos</token><token pos="ncmp000">escaparates</token><token pos="sps00">de</token><token pos="da0fp0">las</token><token pos="ncfp000">tiendas</token><token pos="cc">y</token><token pos="sps00">de</token><token pos="da0mp0">los</token><token pos="ncmp000">centros</token><token pos="aq0cp0">comerciales</token>
		</theme>
		<rheme concept_ref1="c_13" concept_ref2="c_2" concept_ref3="c_21">
			<token pos="vsis3p0">fueron</token><token pos="vmp00pm">tapados</token><token pos="sps00">con</token><mention concept_ref="c_13"><token pos="ncfp000">planchas</token></mention><token pos="sps00">de</token><mention concept_ref="c_21"><token pos="ncfs000">madera</token></mention><token pos="sps00">tras</token><mention concept_ref="c_2"><token pos="da0fs0">la</token><token pos="ncfs000">ruptura</token></mention><token pos="sps00">de</token><token pos="dp3cp0">sus</token><token pos="ncfp000">lunas</token><token pos="da0fs0">la</token><token pos="ncfs000">víspera</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Los antidisturbios impedían ayer acercarse a la zona a los grupos radicales, que intentaban volver a bloquear el acceso a la conferencia de la OMC como el primer día.
		</str>
		<theme>
		</theme>
		<rheme>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="que " />
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Las unidades policiales no vacilaron en detener a quienes desobedecían sus instrucciones de mantenerse alejados.
		</str>
		<theme concept_ref="c_8">
			<token pos="da0fp0">Las</token><token pos="ncfp000">unidades</token><token pos="aq0cp0">policiales</token>
		</theme>
		<rheme>
			<token pos="rn">no</token><token pos="vmis3p0">vacilaron</token><token pos="sps00">en</token><token pos="vmn0000">detener</token><token pos="sps00">a</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 El número de detenidos por los incidentes superaba ya las 240 personas al final de la mañana de ayer, según fuentes policiales.
		</str>
		<theme concept_ref="c_9">
			<token pos="da0ms0">El</token><token pos="ncms000">número</token><token pos="sps00">de</token><token pos="aq0mpp">detenidos</token><token pos="sps00">por</token><token pos="da0mp0">los</token><token pos="nccp000">incidentes</token>
		</theme>
		<rheme concept_ref1="c_8">
			<token pos="vmii3s0">superaba</token><token pos="da0fp0">las</token><token pos="z">240</token><mention concept_ref="c_8"><token pos="ncfp000">personas</token></mention>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="fuentes policiales " />
			<frame type="Process_end" head="final">
				<argument type="Process" dependent="de ayer" /></frame>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Pese al dispositivo de seguridad, grupos de jóvenes, algunos disfrazados de tortugas o de otros animales, intentaron concentrarse en el centro de la ciudad para formar cadenas humanas.
		</str>
		<theme concept_ref="c_10">
			<token pos="ncmp000">grupos</token><token pos="sps00">de</token><token pos="nccp000">jóvenes</token><token pos="fc">,</token><token pos="pi0mp000">algunos</token><token pos="aq0mpp">disfrazados</token><token pos="sps00">de</token><token pos="ncfp000">tortugas</token><token pos="cc">o</token><token pos="sps00">de</token><token pos="di0mp0">otros</token><token pos="ncmp000">animales</token><token pos="fc">,</token>
		</theme>
		<rheme concept_ref1="c_5" concept_ref2="c_9" concept_ref3="c_13" concept_ref4="c_19" concept_ref5="c_20" concept_ref6="c_23">
			<token pos="vmis3p0">intentaron</token><token pos="vmn0000">concentrarse</token><token pos="sps00">en</token><token pos="da0ms0">el</token><mention concept_ref="c_9"><token pos="ncms000">centro</token></mention><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="ncfs000">ciudad</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Las fuerzas de seguridad se reforzaron ayer con la llegada a Seattle de 300 agentes procedentes del resto del estado de Washington.
		</str>
		<theme concept_ref="c_11">
			<token pos="da0fp0">Las</token><token pos="ncfp000">fuerzas</token><token pos="sps00">de</token><token pos="ncfs000">seguridad</token>
		</theme>
		<rheme concept_ref1="c_4" concept_ref2="c_5" concept_ref3="c_14" concept_ref4="c_6" concept_ref5="c_19" concept_ref6="c_21" concept_ref7="c_23">
			<mention concept_ref="c_23"><token pos="p0300000">se</token></mention><token pos="vmis3p0">reforzaron</token><token pos="sps00">con</token><token pos="da0fs0">la</token><token pos="ncfs000">llegada</token><token pos="sps00">a</token><mention concept_ref="c_5"><token pos="np00000">Seattle</token></mention><token pos="sps00">de</token><token pos="z">300</token><token pos="nccp000">agentes</token><token pos="aq0cp0">procedentes</token><token pos="spcms">del</token><token pos="ncms000">resto</token><token pos="spcms">del</token><mention concept_ref="c_14"><token pos="ncms000">estado</token></mention><token pos="sps00">de</token><token pos="np00000">Washington</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Por la mañana, unos 200 miembros de la Guardia Nacional también fueron desplegados por la zona.
		</str>
		<theme concept_ref="c_12">
			<token pos="di0mp0">unos</token><token pos="z">200</token><token pos="ncmp000">miembros</token><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="ncms000">Guardia</token><token pos="aq0ms0">Nacional</token>
		</theme>
		<rheme concept_ref1="c_3" concept_ref2="c_24">
			<token pos="sps00">Por</token><mention concept_ref="c_24"><token pos="da0fs0">la</token><token pos="ncfs000">mañana</token></mention><token pos="rg">también</token><token pos="vsis3p0">fueron</token><token pos="vmp00pm">desplegados</token><token pos="sps00">por</token><mention concept_ref="c_3"><token pos="da0fs0">la</token><token pos="ncfs000">zona</token></mention>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 La policía logró recuperar el control del centro de la ciudad alrededor de las 7 de la tarde del martes ( 4 de la madrugada hora española ) tras desalojar calle por calle a los grupos radicales con gases lacrimógenos y contundentes cargas.
		</str>
		<theme concept_ref="c_13">
			<token pos="da0fs0">La</token><token pos="nccs000">policía</token>
		</theme>
		<rheme concept_ref1="c_5" concept_ref2="c_14" concept_ref3="c_9" concept_ref4="c_13" concept_ref5="c_19" concept_ref6="c_20" concept_ref7="c_21" concept_ref8="c_23">
			<token pos="vmis3s0">logró</token><token pos="vmn0000">recuperar</token><token pos="da0ms0">el</token><token pos="ncms000">control</token><token pos="spcms">del</token><mention concept_ref="c_9"><token pos="ncms000">centro</token></mention><token pos="sps00">de</token><mention concept_ref="c_13"><token pos="da0fs0">la</token><token pos="ncfs000">ciudad</token></mention><token pos="rg">alrededor</token><token pos="sps00">de</token><token pos="da0fp0">las</token><token pos="z">7</token><token pos="sps00">de</token><mention concept_ref="c_14"><token pos="da0fs0">la</token><token pos="ncfs000">tarde</token></mention><token pos="spcms">del</token><token pos="ncms000">martes</token><token pos="fpa">(</token><token pos="z">4</token><token pos="sps00">de</token><token pos="da0fs0">la</token><mention concept_ref="c_21"><token pos="ncfs000">madrugada</token></mention><mention concept_ref="c_20"><token pos="ncfs000">hora</token></mention><token pos="aq0fs0">española</token><token pos="fpt">)</token><token pos="sps00">tras</token><token pos="vmn0000">desalojar</token><token pos="ncfs000">calle</token><token pos="sps00">por</token><token pos="ncfs000">calle</token><token pos="sps00">a</token><token pos="da0mp0">los</token><token pos="ncmp000">grupos</token><token pos="aq0cp0">radicales</token><token pos="sps00">con</token><token pos="ncmp000">gases</token><token pos="aq0mp0">lacrimógenos</token><token pos="cc">y</token><token pos="aq0cp0">contundentes</token><token pos="ncfp000">cargas</token>
		</rheme>
		<semantic_roles>
			<frame type="Being_in_control" head="control">
				<argument type="Controlling_entity" dependent="la" />
				<argument type="Dependent_entity" dependent="recuperar el" /></frame>
			<frame type="Substance" head="gases" />
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 No obstante, durante la noche aún se produjeron algunos enfrentamientos aislados.
		</str>
		<theme>
		</theme>
		<rheme>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Los incidentes del martes fueron protagonizados por jóvenes encapuchados y equipados con máscaras antigás que rompieron escaparates de los centros comerciales, incendiaron contenedores y se enfrentaron repetidamente a la policía.
		</str>
		<theme concept_ref="c_14">
			<token pos="da0mp0">Los</token><token pos="nccp000">incidentes</token><token pos="spcms">del</token><token pos="ncms000">martes</token>
		</theme>
		<rheme concept_ref1="c_23" concept_ref2="c_21">
			<token pos="vsis3p0">fueron</token><token pos="vmp00pm">protagonizados</token><token pos="sps00">por</token><mention concept_ref="c_23"><token pos="nccp000">jóvenes</token></mention><token pos="aq0mp0">encapuchados</token><token pos="cc">y</token><token pos="aq0mpp">equipados</token><token pos="sps00">con</token><mention concept_ref="c_21"><token pos="ncfp000">máscaras</token></mention><token pos="aq0cn0">antigás</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Tras la disolución de la masiva y pacífica manifestación convocada por sindicatos, asociaciones ecologistas y organizaciones no gubernamentales ( ONG ) contra la OMC y la "mundialización de las multinacionales", Paul Schell, alcalde de Seattle, declaró a media tarde del Martes el estado de emergencia y decretó el toque de queda en el centro de la ciudad.
		</str>
		<theme concept_ref="c_15">
			<token pos="np0000l">Paul</token><token pos="np0000l">Schell</token><token pos="fc">,</token><token pos="ncms000">alcalde</token><token pos="sps00">de</token><token pos="np00000">Seattle</token><token pos="fc">,</token>
		</theme>
		<rheme concept_ref1="c_14" concept_ref2="c_5" concept_ref3="c_20" concept_ref4="c_21" concept_ref5="c_23">
			<token pos="vmis3s0">declaró</token><token pos="sps00">a</token><token pos="dn0fs0">media</token><mention concept_ref="c_5"><token pos="ncfs000">tarde</token></mention><token pos="spcms">del</token><token pos="ncms000">Martes</token><mention concept_ref="c_23"><token pos="da0ms0">el</token><token pos="ncms000">estado</token></mention><token pos="sps00">de</token><token pos="ncfs000">emergencia</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 "Esto no volverá a ocurrir", afirmó Schell en una entrevista televisada.
		</str>
		<theme>
		</theme>
		<rheme>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 "Vamos a utilizar cada medio de que dispongamos y actuaremos inmediatamente contra cualquier desmán en las calles", añadió.
		</str>
		<theme>
		</theme>
		<rheme>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 Toque de queda vigente.
		</str>
		<theme>
		</theme>
		<rheme>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 En principio, el toque de queda y el estado de emergencia se mantendrán hasta el final de la reunión.
		</str>
		<theme concept_ref="c_16">
			<token pos="da0ms0">el</token><token pos="ncms000">toque</token><token pos="spcms">de</token><token pos="ncms000">queda</token><token pos="cc">y</token><token pos="da0ms0">el</token><token pos="ncms000">estado</token><token pos="sps00">de</token><token pos="ncfs000">emergencia</token>
		</theme>
		<rheme concept_ref1="c_4" concept_ref2="c_18" concept_ref3="c_23">
			<mention concept_ref="c_23"><token pos="p0000000">se</token></mention><token pos="vmif3p0">mantendrán</token><token pos="sps00">hasta</token><mention concept_ref="c_4"><token pos="da0ms0">el</token><token pos="ncms000">final</token></mention><token pos="sps00">de</token><mention concept_ref="c_18"><token pos="da0fs0">la</token><token pos="ncfs000">reunión</token></mention>
		</rheme>
		<semantic_roles>
			<frame type="Process_end" head="final">
				<argument type="Process" dependent="de la" /></frame>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 La noche del martes, unos 2.000 manifestantes radicales se hicieron con el control de los cruces de las calles alrededor del centro de congresos para impedir el acceso de las autoridades a la conferencia de la OMC.
		</str>
		<theme concept_ref="c_17">
			<token pos="di0mp0">unos</token><token pos="z">2.000</token><token pos="nccp000">manifestantes</token><token pos="aq0cp0">radicales</token>
		</theme>
		<rheme concept_ref1="c_3" concept_ref2="c_5" concept_ref3="c_14" concept_ref4="c_8" concept_ref5="c_9" concept_ref6="c_1" concept_ref7="c_19" concept_ref8="c_22" concept_ref9="c_21" concept_ref10="c_23">
			<mention concept_ref="c_23"><token pos="p0300000">se</token></mention><token pos="vmis3p0">hicieron</token><token pos="sps00">con</token><token pos="da0ms0">el</token><token pos="ncms000">control</token><token pos="sps00">de</token><mention concept_ref="c_1"><token pos="da0mp0">los</token><token pos="ncmp000">cruces</token></mention><token pos="sps00">de</token><token pos="da0fp0">las</token><token pos="ncfp000">calles</token><token pos="rg">alrededor</token><token pos="spcms">del</token><mention concept_ref="c_9"><token pos="ncms000">centro</token></mention><token pos="sps00">de</token><mention concept_ref="c_14"><token pos="ncmp000">congresos</token></mention><token pos="sps00">para</token><token pos="vmn0000">impedir</token><token pos="da0ms0">el</token><token pos="ncms000">acceso</token><token pos="sps00">de</token><token pos="da0fp0">las</token><token pos="ncfp000">autoridades</token><token pos="sps00">a</token><token pos="da0fs0">la</token><token pos="ncfs000">conferencia</token><token pos="sps00">de</token><mention concept_ref="c_3"><token pos="da0fs0">la</token><token pos="np00000">OMC</token></mention>
		</rheme>
		<semantic_roles>
			<frame type="Being_in_control" head="control">
				<argument type="Dependent_entity" dependent="el" /></frame>
		</semantic_roles>
	</sentence>
	<sentence>
		<str>			
			 La policía, que tardó varias horas en controlar la situación, cargó con gases lacrimógenos para desalojar a esos grupos de las inmediaciones del centro de reuniones.
		</str>
		<theme concept_ref="c_18">
			<token pos="da0fs0">La</token><token pos="nccs000">policía</token><token pos="fc">,</token><token pos="pr0cn000">que</token><token pos="vmis3s0">tardó</token><token pos="di0fp0">varias</token><token pos="ncfp000">horas</token><token pos="sps00">en</token><token pos="vmn0000">controlar</token><token pos="da0fs0">la</token><token pos="ncfs000">situación</token><token pos="fc">,</token>
		</theme>
		<rheme concept_ref1="c_5" concept_ref2="c_9" concept_ref3="c_10" concept_ref4="c_8" concept_ref5="c_1" concept_ref6="c_19" concept_ref7="c_21" concept_ref8="c_23">
			<token pos="vmis3s0">cargó</token><token pos="sps00">con</token><mention concept_ref="c_21"><token pos="ncmp000">gases</token></mention><token pos="aq0mp0">lacrimógenos</token><token pos="sps00">para</token><token pos="vmn0000">desalojar</token><token pos="sps00">a</token><mention concept_ref="c_10"><token pos="dd0mp0">esos</token><token pos="ncmp000">grupos</token></mention><token pos="sps00">de</token><mention concept_ref="c_8"><token pos="da0fp0">las</token><token pos="ncfp000">inmediaciones</token></mention><token pos="spcms">del</token><mention concept_ref="c_9"><token pos="ncms000">centro</token></mention><token pos="sps00">de</token><mention concept_ref="c_1"><token pos="ncfp000">reuniones</token></mention>
		</rheme>
		<semantic_roles>
			<frame type="Substance" head="gases" />
		</semantic_roles>
	</sentence>
	
</text>