<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
    <!ELEMENT text (concepts, sentence+)>
        <!ATTLIST text id CDATA #REQUIRED>
    <!ELEMENT concepts (concept+)>
        <!ELEMENT concept (#PCDATA)>
            <!ATTLIST concept id ID #REQUIRED>
    <!ELEMENT sentence (theme, rheme, semantic_roles)>
        <!ELEMENT theme (token*)>
            <!ATTLIST theme concept_ref IDREF #REQUIRED>
        <!ELEMENT rheme (token*)>
            <!ATTLIST rheme concept_ref1 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref2 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref3 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref4 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref5 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref6 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref7 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref8 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref9 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref10 IDREF #IMPLIED>
        <!ELEMENT token (#PCDATA)>
            <!ATTLIST token pos CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame|main_frame)*>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT main_frame (argument*)>
            <!ATTLIST main_frame type CDATA #REQUIRED>
            <!ATTLIST main_frame head CDATA #REQUIRED>
        <!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="t4-12_ssd_annotated_recursive">


	<concepts>
		<concept id="c_0">los mejores guerreros del mundo , los hunos</concept>
		<concept id="c_1">Pocos</concept>
		<concept id="c_2">La buena ciudadanía</concept>
		<concept id="c_3">El camaleón</concept>
		<concept id="c_4">La Tierra</concept>
		<concept id="c_5">con un tema tan metafísicamente imposible</concept>
		<concept id="c_6">cuernos</concept>
		<concept id="c_8">un tema</concept>
		<concept id="c_9">la cárcel</concept>
	</concepts>

	<sentence>
		<theme concept_ref="c_0">
			<token pos="da0mp0">los</token><token pos="aq0cp0">mejores</token><token pos="ncmp000">guerreros</token><token pos="spcms">del</token><token pos="ncms000">mundo</token><token pos="fc">,</token><token pos="da0mp0">los</token><token pos="ncmp000">hunos</token>
		</theme>
		<rheme concept_ref1="c_0" concept_ref2="c_6">
			<token pos="sps00">con</token><token pos="dn0cp0">dos</token><token pos="ncmp000">cuernos</token><token pos="vmii3p0">tenían</token>
		</rheme>
		<semantic_roles>
			<frame type="Cardinal_numbers" head="dos" />
			<frame type="Political_locales" head="mundo" />
			<frame type="Required_event" head="mejores" />
			<frame type="Sufficiency" head="bastante">
				<argument type="Item" dependent="los hunos con dos cuernos" /></frame>
			<frame type="Time_vector" head="Antes">
				<argument type="Landmark_event" dependent="ellos los mejores guerreros del mundo, los hunos con dos cuernos tenían bastante" /></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_1">
			<token pos="pi0mp000">Pocos</token>
		</theme>
		<rheme concept_ref1="c_5" concept_ref2="c_8">
			<token pos="p0300000">se</token><token pos="vaic3p0">habrían</token><token pos="vmp00sm">atrevido</token><token pos="sps00">con</token><token pos="di0ms0">un</token><token pos="ncms000">tema</token><token pos="rg">tan</token><token pos="rg">metafísicamente</token><token pos="aq0cs0">imposible</token>
		</rheme>
		<semantic_roles>
			<frame type="Daring" head="atrevido">
				<argument type="Action" dependent="con un tema tan metafísicamente imposible" /></frame>
			<main_frame type="Daring" head="atrevido">
				<argument type="Action" dependent="con un tema tan metafísicamente imposible" /></main_frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_0">
			<token pos="da0fs0">La</token><token pos="ncfs000">monarquía</token><token pos="sps00">de</token><token pos="np0000l">Alfonso</token><token pos="np0000l">XIII</token><token pos="sps00">a</token><token pos="pr0cs000">quien</token><token pos="pi0mp000">todos</token><token pos="vmii3p0">consideraban</token><token pos="aq0cs0">gafe</token><token pos="sps00">por</token><token pos="da0ms0">el</token><token pos="aq0cs0">numeral</token><token pos="fg">-</token><token pos="fg">-</token><token pos="sps00">de</token><token pos="da0mp0">los</token><token pos="ncmn000">idus</token><token pos="aq0mp0">romanos</token><token pos="fg">-</token><token pos="fg">-</token>
		</theme>
		<rheme concept_ref1="c_3" concept_ref2="c_0" concept_ref3="c_5" concept_ref4="c_6" concept_ref5="c_9">
			<token pos="p0300000">se</token><token pos="vmis3s0">hundió</token><token pos="sps00">por</token><token pos="van0000">haberse</token><token pos="vmp00sm">atrevido</token><token pos="sps00">a</token><token pos="vmn0000">meter</token><token pos="sps00">en</token><token pos="da0fs0">la</token><token pos="ncfs000">cárcel</token><token pos="sps00">a</token><token pos="ncfp000">personas</token><token pos="rg">tan</token><token pos="rg">inocentemente</token><token pos="aq0cp0">nobles</token><token pos="cs">como</token><token pos="np00000">Fernando</token><token pos="sps00">de</token><token pos="da0fs0">los</token><token pos="np00000">Ríos</token><token pos="fc">,</token><token pos="rg">tan</token><token pos="rg">genialmente</token><token pos="aq0fp0">líricas</token><token pos="cs">como</token><token pos="ncms000">Valle</token><token pos="np00000">Inclán</token><token pos="cc">y</token><token pos="rg">tan</token><token pos="rg">poco</token><token pos="aq0fp0">peligrosas</token><token pos="cs">como</token><token pos="pp1csn00">yo</token>
		</rheme>
		<semantic_roles>
			<main_frame type="Categorization" head="consideraban" />
			<frame type="Categorization" head="consideraban" />
			<frame type="Categorization" head="consideraban" />
			<frame type="Categorization" head="consideraban" />
			<frame type="Categorization" head="consideraban" />
			<frame type="Causation" head="por haberse">
				<argument type="Effect" dependent="monarquía de Alfonso XIII a quien todos consideraban" />
				<argument type="Cause" dependent="numeral - - de los idus romanos - - se hundió por haberse atrevido a meter en la cárcel a personas tan inocentemente" /></frame>
			<frame type="Causation" head="por haberse">
				<argument type="Effect" dependent="monarquía de Alfonso XIII a quien todos consideraban" />
				<argument type="Cause" dependent="numeral - - de los idus romanos - - se hundió por haberse atrevido a meter en la cárcel a personas tan inocentemente" /></frame>
			<main_frame type="Causation" head="por haberse">
				<argument type="Effect" dependent="monarquía de Alfonso XIII a quien todos consideraban" />
				<argument type="Cause" dependent="numeral - - de los idus romanos - - se hundió por haberse atrevido a meter en la cárcel a personas tan inocentemente" /></main_frame>
			<frame type="Causation" head="por haberse">
				<argument type="Effect" dependent="monarquía de Alfonso XIII a quien todos consideraban" />
				<argument type="Cause" dependent="numeral - - de los idus romanos - - se hundió por haberse atrevido a meter en la cárcel a personas tan inocentemente" /></frame>
			<frame type="Causation" head="por haberse">
				<argument type="Effect" dependent="monarquía de Alfonso XIII a quien todos consideraban" />
				<argument type="Cause" dependent="numeral - - de los idus romanos - - se hundió por haberse atrevido a meter en la cárcel a personas tan inocentemente" /></frame>
			<frame type="Daring" head="atrevido">
				<argument type="Action" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<frame type="Daring" head="atrevido">
				<argument type="Action" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<frame type="Daring" head="atrevido">
				<argument type="Action" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<main_frame type="Daring" head="atrevido">
				<argument type="Action" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></main_frame>
			<frame type="Daring" head="atrevido">
				<argument type="Action" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<frame type="People" head="personas" />
			<frame type="People" head="personas" />
			<frame type="People" head="personas" />
			<frame type="People" head="personas" />
			<frame type="People" head="personas" />
			<frame type="Placing" head="se">
				<argument type="Goal" dependent="tan inocentemente nobles como" /></frame>
			<frame type="Placing" head="se">
				<argument type="Goal" dependent="tan inocentemente nobles como" /></frame>
			<frame type="Placing" head="se">
				<argument type="Goal" dependent="tan inocentemente nobles como" /></frame>
			<frame type="Placing" head="se">
				<argument type="Goal" dependent="tan inocentemente nobles como" /></frame>
			<frame type="Placing" head="se">
				<argument type="Goal" dependent="tan inocentemente nobles como" /></frame>
			<frame type="Possession" head="se">
				<argument type="Possession" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<frame type="Possession" head="se">
				<argument type="Possession" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<frame type="Possession" head="se">
				<argument type="Possession" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<frame type="Possession" head="se">
				<argument type="Possession" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<frame type="Possession" head="se">
				<argument type="Possession" dependent="a meter en la cárcel a personas tan inocentemente nobles como" /></frame>
			<frame type="Risky_situation" head="peligrosas">
				<argument type="Situation" dependent="como yo" /></frame>
			<frame type="Risky_situation" head="peligrosas">
				<argument type="Situation" dependent="como yo" /></frame>
			<frame type="Risky_situation" head="peligrosas">
				<argument type="Situation" dependent="como yo" /></frame>
			<frame type="Risky_situation" head="peligrosas">
				<argument type="Situation" dependent="como yo" /></frame>
			<frame type="Risky_situation" head="peligrosas">
				<argument type="Situation" dependent="como yo" /></frame>
			<frame type="Similarity" head="como">
				<argument type="Entity_1" dependent="tan poco peligrosas" /></frame>
			<frame type="Similarity" head="como">
				<argument type="Entity_1" dependent="tan poco peligrosas" /></frame>
			<frame type="Similarity" head="como">
				<argument type="Entity_1" dependent="tan poco peligrosas" /></frame>
			<frame type="Similarity" head="como">
				<argument type="Entity_1" dependent="tan poco peligrosas" /></frame>
			<frame type="Similarity" head="como">
				<argument type="Entity_1" dependent="tan poco peligrosas" /></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_0">
			<token pos="di0mp0">Todos</token><token pos="da0mp0">los</token><token pos="ncmp000">primitos</token><token pos="sps00">de</token><token pos="da0fp0">las</token><token pos="ncfp000">niñas</token>
		</theme>
		<rheme concept_ref1="c_6">
			<token pos="vmip3p0">orinan</token><token pos="sps00">por</token><token pos="di0ms0">un</token><token pos="ncms000">dedo</token><token pos="aq0cs0">meñique</token>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="ellos " />
			<frame type="Body_parts" head="dedo" />
			<frame type="Calendric_unit" head="edad" />
			<frame type="Communicate_categorization" head="Definiciones">
				<argument type="Speaker" dependent="niños de" /></frame>
			<frame type="Identicality" head="la misma" />
			<frame type="People" head="niñas" />
			<frame type="People_by_age" head="niñas">
				<argument type="Person" dependent="los niños de la misma edad" /></frame>
			<frame type="Statement" head="dicen" />
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_2">
			<token pos="da0fs0">La</token><token pos="aq0fs0">buena</token><token pos="ncfs000">ciudadanía</token>
		</theme>
		<rheme concept_ref1="c_2" concept_ref2="c_4" concept_ref3="c_8">
			<token pos="vmip3s0">consiste</token><token pos="sps00">en</token><token pos="vmn0000">cultivar</token><token pos="da0fs0">la</token><token pos="ncfs000">prudencia</token><token pos="cc">y</token><token pos="vmn0000">preferirla</token><token pos="sps00">a</token><token pos="da0fs0">la</token><token pos="ncfs000">aventura</token>
		</rheme>
		<semantic_roles>
			<frame type="Agriculture" head="cultivar" />
			<main_frame type="Agriculture" head="cultivar" />
			<frame type="Agriculture" head="cultivar" />
			<frame type="Calendric_unit" head="siglo" />
			<frame type="Calendric_unit" head="siglo" />
			<frame type="Calendric_unit" head="siglo" />
			<frame type="Cardinal_numbers" head="tres" />
			<frame type="Cardinal_numbers" head="tres" />
			<frame type="Cardinal_numbers" head="tres" />
			<frame type="Desirability" head="buena" />
			<frame type="Desirability" head="buena" />
			<frame type="Desirability" head="buena" />
			<frame type="Event_instance" head="dos veces">
				<argument type="Event" dependent="ciudadanía razonable nos lleva al caos con tres o cuatro guerras cada siglo" /></frame>
			<frame type="Event_instance" head="dos veces">
				<argument type="Event" dependent="ciudadanía razonable nos lleva al caos con tres o cuatro guerras cada siglo" /></frame>
			<frame type="Event_instance" head="dos veces">
				<argument type="Event" dependent="ciudadanía razonable nos lleva al caos con tres o cuatro guerras cada siglo" /></frame>
			<frame type="Frequency" head="cada" />
			<frame type="Frequency" head="cada" />
			<frame type="Frequency" head="cada" />
			<frame type="Hostile_encounter" head="guerras" />
			<frame type="Hostile_encounter" head="guerras" />
			<frame type="Hostile_encounter" head="guerras" />
			<frame type="Leadership" head="lleva">
				<argument type="Governed" dependent="nos lleva al caos con tres o cuatro guerras" /></frame>
			<frame type="Leadership" head="lleva">
				<argument type="Governed" dependent="nos lleva al caos con tres o cuatro guerras" /></frame>
			<frame type="Leadership" head="lleva">
				<argument type="Governed" dependent="nos lleva al caos con tres o cuatro guerras" /></frame>
			<frame type="Opinion" head="pensándolo">
				<argument type="Opinion" dependent="dos veces la" />
				<argument type="Opinion" dependent="ciudadanía razonable nos lleva al caos con tres o cuatro guerras cada siglo" /></frame>
			<frame type="Opinion" head="pensándolo">
				<argument type="Opinion" dependent="dos veces la" />
				<argument type="Opinion" dependent="ciudadanía razonable nos lleva al caos con tres o cuatro guerras cada siglo" /></frame>
			<frame type="Opinion" head="pensándolo">
				<argument type="Opinion" dependent="dos veces la" />
				<argument type="Opinion" dependent="ciudadanía razonable nos lleva al caos con tres o cuatro guerras cada siglo" /></frame>
			<frame type="Proportional_quantity" head="en" />
			<frame type="Proportional_quantity" head="en" />
			<frame type="Proportional_quantity" head="en" />
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_3">
			<token pos="da0ms0">El</token><token pos="ncms000">camaleón</token>
		</theme>
		<rheme concept_ref1="c_1">
			<token pos="rn">no</token><token pos="vmip3s0">tiene</token><token pos="ncms000">color</token><token pos="cc">ni</token><token pos="ncfs000">actividad</token>
		</rheme>
		<semantic_roles>
			<frame type="Being_named" head="nombre" />
			<frame type="Giving" head="lo">
				<argument type="Theme" dependent="nombre tan contradictoriamente" /></frame>
			<frame type="Intentionally_act" head="actividad" />
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_4">
			<token pos="da0fs0">La</token><token pos="np0000a">Tierra</token>
		</theme>
		<rheme>
			<token pos="p0300000">se</token><token pos="vmip3s0">hace</token><token pos="aq0fs0">vieja</token>
		</rheme>
		<semantic_roles>
			<frame type="Activity_start" head="entrar" />
			<frame type="Age" head="vieja" />
			<frame type="Desirable_event" head="debería">
				<argument type="State_of_affairs" dependent="entrar ya en la menopausia" /></frame>
			<frame type="Getting" head="engendrando">
				<argument type="Recipient" dependent="La Tierra" /></frame>
			<frame type="Process_continue" head="sigue">
				<argument type="Event" dependent="fornicando y engendrando monstruos" /></frame>
		</semantic_roles>
	</sentence>


</text>