<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
    <!ELEMENT text (concepts, sentence+)>
        <!ATTLIST text id CDATA #REQUIRED>
    <!ELEMENT concepts (concept+)>
        <!ELEMENT concept (#PCDATA)>
            <!ATTLIST concept id ID #REQUIRED>
    <!ELEMENT sentence (theme, rheme, semantic_roles)>
        <!ELEMENT theme (token*)>
            <!ATTLIST theme concept_ref IDREF #REQUIRED>
        <!ELEMENT rheme (token*)>
            <!ATTLIST rheme concept_ref1 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref2 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref3 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref4 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref5 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref6 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref7 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref8 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref9 IDREF #IMPLIED>
            <!ATTLIST rheme concept_ref10 IDREF #IMPLIED>
        <!ELEMENT token (#PCDATA)>
            <!ATTLIST token pos CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame|main_frame)*>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT main_frame (argument*)>
            <!ATTLIST main_frame type CDATA #REQUIRED>
            <!ATTLIST main_frame head CDATA #REQUIRED>
        <!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="t4-2_ssd_annotated_recursive">


	<concepts>
		<concept id="c_0">el nacer</concept>
		<concept id="c_1">El amor</concept>
		<concept id="c_2">el agua y el fuego</concept>
		<concept id="c_3">que</concept>
		<concept id="c_4">El león</concept>
		<concept id="c_5">partido que tiene un sólo</concept>
		<concept id="c_6">una evasión</concept>
		<concept id="c_10">los besos</concept>
	</concepts>

	<sentence>
		<theme concept_ref="c_0">
			<token pos="da0ms0">el</token><token pos="ncms000">nacer</token>
		</theme>
		<rheme concept_ref1="c_3" concept_ref2="c_4" concept_ref3="c_6">
			<token pos="vsii3s0">era</token><token pos="di0fs0">una</token><token pos="ncfs000">evasión</token><token pos="fpa">(</token><token pos="fg">-</token><token pos="sps00">de</token><token pos="pt0cs000">qué</token><token pos="fit">?</token><token pos="fpt">)</token><token pos="da0ms0">el</token><token pos="ncms000">morir</token><token pos="di0fs0">una</token><token pos="ncfs000">emigración</token><token pos="fpa">(</token><token pos="fg">-</token><token pos="sps00">a</token><token pos="pt000000">dónde</token><token pos="fit">?</token>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="Eso " />
			<frame type="Being_born" head="nacer" />
			<frame type="Death" head="morir">
				<argument type="Protagonist" dependent="una emigración" /></frame>
			<frame type="Departing" head="evasión" />
			<frame type="Manufacturing" head="hizo" />
			<frame type="Remembering_experience" head="recordar">
				<argument type="Salient_entity" dependent="nacer era una evasión ( - de qué ? ) y el morir una emigración ( - a dónde" /></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_1">
			<token pos="da0ms0">El</token><token pos="ncms000">amor</token>
		</theme>
		<rheme concept_ref1="c_0" concept_ref2="c_6" concept_ref3="c_10">
			<token pos="p0000000">se</token><token pos="vmip3s0">cuenta</token><token pos="sps00">por</token><token pos="da0fs0">la</token><token pos="ncfs000">frecuencia</token><token pos="sps00">de</token><token pos="da0mp0">los</token><token pos="ncmp000">besos</token>
		</rheme>
		<semantic_roles>
			<frame type="Cause_emotion" head="insultos" />
			<frame type="Frequency" head="frecuencia de">
				<argument type="Event" dependent="insultos" /></frame>
			<frame type="Manipulation" head="besos" />
			<frame type="Telling" head="se">
				<argument type="Message" dependent="por la frecuencia de los besos y la pasión por la frecuencia de los insultos" /></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_2">
			<token pos="da0ms0">el</token><token pos="ncfs000">agua</token><token pos="cc">y</token><token pos="da0ms0">el</token><token pos="ncms000">fuego</token>
		</theme>
		<rheme concept_ref1="c_0" concept_ref2="c_2" concept_ref3="c_10">
			<token pos="vsip3p0">son</token><token pos="ncmp000">dioses</token><token pos="da0ms0">el</token><token pos="ncms000">rayo</token><token pos="dp3cs0">su</token><token pos="rg">más</token><token pos="aq0cs0">elocuente</token><token pos="cc">y</token><token pos="aq0cs0">eficaz</token><token pos="nccs000">agente</token><token pos="sps00">de</token><token pos="ncfp000">relaciones</token><token pos="aq0fp0">públicas</token>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="Los mayas " />
			<frame type="Active_substance" head="agente" />
			<frame type="Certainty" head="creen">
				<argument type="Cognizer" dependent="mayas" />
				<argument type="Content" dependent="agua y el fuego son dioses y el rayo su más elocuente y eficaz agente de relaciones públicas" /></frame>
			<frame type="Fire_burning" head="fuego" />
			<frame type="Relation" head="de relaciones" />
			<frame type="Usefulness" head="eficaz">
				<argument type="Entity" dependent="agente de relaciones públicas" /></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_3">
			<token pos="pr0cn000">que</token>
		</theme>
		<rheme concept_ref1="c_6">
			<token pos="vmip3s0">tiene</token><token pos="dn0ms0">un</token><token pos="aq0ms0">sólo</token><token pos="nccs000">militante</token><token pos="pp1csn00">Yo</token>
		</rheme>
		<semantic_roles>
			<frame type="Aggregate" head="partido" />
			<frame type="Cardinal_numbers" head="un" />
			<frame type="Membership" head="partido" />
			<main_frame type="Possession" head="tiene">
				<argument type="Possession" dependent="partido que tiene un sólo" /></main_frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme concept_ref="c_4">
			<token pos="da0ms0">El</token><token pos="ncms000">león</token>
		</theme>
		<rheme>
			<token pos="vmip3s0">tiene</token><token pos="ncfs000">fama</token><token pos="sps00">de</token><token pos="aq0cs0">noble</token>
		</rheme>
		<semantic_roles>
			<frame type="Body_parts" head="coima" />
			<frame type="Fame" head="fama">
				<argument type="Entity" dependent="El león" />
				<argument type="Reason" dependent="de noble" /></frame>
			<frame type="Hunting" head="caza" />
			<frame type="Manufacturing" head="hace" />
			<frame type="Political_locales" head="naciones" />
			<frame type="Residence" head="vive" />
			<frame type="Similarity" head="como">
				<argument type="Entity_2" dependent="el rufián del prostíbulo cuya coima - hace cabritos -, para darle de comer" /></frame>
			<frame type="Using" head="usan">
				<argument type="Agent" dependent="algunas naciones" /></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


</text>