<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

    <!DOCTYPE text [
    	<!ELEMENT text (sentence+)>
    	    <!ATTLIST text id CDATA #REQUIRED>
    	<!ELEMENT sentence (str, theme, rheme, semantic_roles)>
    		<!ELEMENT str (#PCDATA)>
    		<!ELEMENT theme (token*)>
    		<!ELEMENT rheme (token*)>
    		<!ELEMENT token (#PCDATA)>
    		    <!ATTLIST token pos CDATA #REQUIRED>
    		<!ELEMENT semantic_roles (frame|main_frame)*>
    		<!ELEMENT frame (argument*)>
                <!ATTLIST frame type CDATA #REQUIRED>
                <!ATTLIST frame head CDATA #REQUIRED>
    		<!ELEMENT main_frame (argument*)>
                <!ATTLIST main_frame type CDATA #REQUIRED>
                <!ATTLIST main_frame head CDATA #REQUIRED>
    		<!ELEMENT argument EMPTY>
                <!ATTLIST argument type CDATA #REQUIRED>
                <!ATTLIST argument dependent CDATA #REQUIRED>
    ]>


    <text id="2_20010702_ssd">


	<sentence>
		<str>
			 En los últimos años, la demanda de electricidad ha experimentado un aumento continuo que, según prevén los expertos, seguirá en el futuro.
		</str>
		<theme>
			<token pos="da0fs0">la</token><token pos="ncfs000">demanda</token><token pos="sps00">de</token><token pos="ncfs000">electricidad</token>
		</theme>
		<rheme>
			<token pos="sps00">En</token><token pos="da0mp0">los</token><token pos="ao0mp0">últimos</token><token pos="ncmp000">años</token><token pos="vaip3s0">ha</token><token pos="vmp00sm">experimentado</token><token pos="di0ms0">un</token><token pos="ncms000">aumento</token><token pos="aq0ms0">continuo</token>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="los expertos "></frame>
			<frame type="Calendric_unit" head="años">
				<argument type="Relative_time" dependent="últimos"/></frame>
			<frame type="Change_position_on_a_scale" head="aumento">
				<argument type="Item" dependent=", según prevén los expertos , seguirá en el futuro"/></frame>
			<frame type="Electricity" head="electricidad"></frame>
			<frame type="Expertise" head="expertos"></frame>
			<frame type="Perception_experience" head="según">
				<argument type="Time" dependent="En los últimos años"/>
				<argument type="Perceiver_passive" dependent="la demanda de electricidad"/>
				<argument type="Phenomenon" dependent="aumento continuo que , según prevén los expertos , seguirá en el futuro"/></frame>
			<frame type="Predicting" head="futuro">
				<argument type="Speaker" dependent="expertos"/>
				<argument type="Eventuality" dependent="seguirá en el futuro"/></frame>
			<frame type="Process_continue" head="continuo">
				<argument type="Circumstances" dependent="en el futuro"/></frame>
			<frame type="Request" head="demanda">
				<argument type="Message" dependent="de electricidad ha experimentado un aumento continuo que , según prevén los expertos , seguirá en el futuro"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 Así, Endesa calcula que este año la demanda en Catalunya crecerá entre un 5 y 6%.
		</str>
		<theme>
			<token pos="da0fs0">la</token><token pos="ncfs000">demanda</token><token pos="sps00">en</token><token pos="np00000">Catalunya</token>
		</theme>
		<rheme>
			<token pos="vmif3s0">crecerá</token><token pos="sps00">entre</token><token pos="di0ms0">un</token><token pos="z">5</token><token pos="sps00">y</token><token pos="zp">6%</token>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="Endesa "></frame>
			<frame type="Calendric_unit" head="año"></frame>
			<main_frame type="Change_position_on_a_scale" head="crecerá">
				<argument type="Attribute" dependent="este año la demanda en Catalunya"/>
				<argument type="Attribute" dependent="entre un 5 y 6 %"/></main_frame>
			<frame type="Estimating" head="calcula que">
				<argument type="Estimation" dependent="que este año la demanda en Catalunya crecerá entre un 5 y 6 % ."/></frame>
			<frame type="Interior_profile_relation" head="en">
				<argument type="Figure" dependent="este año la demanda"/>
				<argument type="Ground" dependent="Catalunya"/></frame>
			<frame type="Interior_profile_relation" head="entre">
				<argument type="Ground" dependent="5 y 6 %"/></frame>
			<frame type="Request" head="demanda">
				<argument type="Speaker" dependent="en Catalunya"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 La gran diferencia es que ahora el consumo de electricidad en los meses de verano no es muy inferior al que se produce durante el frío invierno y que, debido a la gran afluencia de visitantes, los problemas de capacidad se originan en las zonas turísticas de la costa.
		</str>
		<theme>
			<token pos="da0fs0">La</token><token pos="aq0cs0">gran</token><token pos="ncfs000">diferencia</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="cs">que</token><token pos="rg">ahora</token><token pos="da0ms0">el</token><token pos="ncms000">consumo</token><token pos="sps00">de</token><token pos="ncfs000">electricidad</token><token pos="sps00">en</token><token pos="da0mp0">los</token><token pos="ncmp000">meses</token><token pos="sps00">de</token><token pos="ncms000">verano</token><token pos="rn">no</token><token pos="vsip3s0">es</token><token pos="rg">muy</token><token pos="aq0cs0">inferior</token><token pos="spcms">al</token><token pos="cc">y</token><token pos="cs">que</token><token pos="fc">,</token><token pos="vmip2s0">debido</token><token pos="sps00">a</token><token pos="da0fs0">la</token><token pos="aq0cs0">gran</token><token pos="ncfs000">afluencia</token><token pos="sps00">de</token><token pos="nccp000">visitantes</token><token pos="fc">,</token><token pos="da0mp0">los</token><token pos="ncmp000">problemas</token><token pos="sps00">de</token><token pos="ncfs000">capacidad</token><token pos="p0300000">se</token><token pos="vmip3p0">originan</token><token pos="sps00">en</token><token pos="da0fp0">las</token><token pos="ncfp000">zonas</token><token pos="aq0fp0">turísticas</token><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="ncfs000">costa</token>
		</rheme>
		<semantic_roles>
			<frame type="Arriving" head="afluencia">
				<argument type="Theme" dependent="de visitantes"/></frame>
			<frame type="Calendric_unit" head="invierno">
				<argument type="Relative_time" dependent="frío"/></frame>
			<main_frame type="Calendric_unit" head="meses">
				<argument type="Relative_time" dependent="verano"/></main_frame>
			<frame type="Calendric_unit" head="verano"></frame>
			<frame type="Capability" head="capacidad">
				<argument type="Event" dependent="problemas"/></frame>
			<frame type="Change_position_on_a_scale" head="inferior"></frame>
			<frame type="Electricity" head="electricidad"></frame>
			<frame type="Interior_profile_relation" head="en">
				<argument type="Figure" dependent="problemas de capacidad se originan"/>
				<argument type="Ground" dependent="las zonas turísticas de la costa"/></frame>
			<frame type="Locale" head="zonas">
				<argument type="Descriptor" dependent="turísticas"/>
				<argument type="Formational_cause" dependent="de la costa"/></frame>
			<frame type="Manufacturing" head="produce">
				<argument type="Product" dependent="es"/></frame>
			<frame type="Medical_conditions" head="frío"></frame>
			<frame type="Non-commutative_statement" head="diferencia"></frame>
			<main_frame type="Origin" head="originan">
				<argument type="Entity" dependent="problemas de capacidad"/>
				<argument type="Origin" dependent="en las zonas turísticas de la costa"/></main_frame>
			<frame type="Predicament" head="problemas">
				<argument type="Situation" dependent="las zonas turísticas de la costa"/></frame>
			<frame type="Relational_natural_features" head="la costa">
				<argument type="Descriptor" dependent="de"/></frame>
			<frame type="Size" head="gran">
				<argument type="Entity" dependent="afluencia de visitantes"/></frame>
			<frame type="Temporal_collocation" head="ahora">
				<argument type="Trajector_event" dependent="el consumo de electricidad en los meses de verano"/>
				<argument type="Trajector_event" dependent="muy inferior al que se produce durante el frío invierno y que , debido a la gran afluencia de visitantes ,"/></frame>
			<main_frame type="Visiting" head="visitantes"></main_frame>
		</semantic_roles>
	</sentence>


</text>