<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
	<!ELEMENT text (sentence+)>
	    <!ATTLIST text id CDATA #REQUIRED>
	<!ELEMENT sentence (str, theme, rheme, semantic_roles)>
		<!ELEMENT str (#PCDATA)>
		<!ELEMENT theme (token*)>
		<!ELEMENT rheme (token*)>
		<!ELEMENT token (#PCDATA)>
		    <!ATTLIST token pos CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame|main_frame)*>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT main_frame (argument*)>
            <!ATTLIST main_frame type CDATA #REQUIRED>
            <!ATTLIST main_frame head CDATA #REQUIRED>
		<!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="8_20011202_ssd">


	<sentence>
		<str>
			 El sistema de elección del rector es mayoritariamente descalificado.
		</str>
		<theme>
			<token pos="da0ms0">El</token><token pos="ncms000">sistema</token><token pos="sps00">de</token><token pos="ncfs000">elección</token><token pos="spcms">del</token><token pos="ncms000">rector</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="rg">mayoritariamente</token><token pos="aq0msp">descalificado</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 Los detractores de la medida acusan al PP de defender con ahínco una fórmula "exótica", de acuerdo con el adjetivo benévolo utilizado por el conseller de Universitats, Andreu Mas-Colell, con la mirada puesta en los dividendos que les reportará.
		</str>
		<theme>
			<token pos="da0mp0">Los</token><token pos="ncmp000">detractores</token><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="ncfs000">medida</token>
		</theme>
		<rheme>
			<token pos="vmip3p0">acusan</token><token pos="spcms">al</token><token pos="np00000">PP</token><token pos="sps00">de</token><token pos="vmn0000">defender</token><token pos="sps00">con</token><token pos="ncms000">ahínco</token><token pos="di0fs0">una</token><token pos="ncfs000">fórmula</token><token pos="fe">quot;</token><token pos="aq0fs0">exótica</token><token pos="fe">quot;</token><token pos="fc">,</token><token pos="sps00">de</token><token pos="ncfs000">acuerdo</token><token pos="sps00">con</token><token pos="da0ms0">el</token><token pos="ncms000">adjetivo</token><token pos="aq0ms0">benévolo</token><token pos="aq0msp">utilizado</token><token pos="sps00">por</token><token pos="da0ms0">el</token><token pos="ncms000">conseller</token><token pos="sps00">de</token><token pos="np00000">Universitats</token><token pos="fc">,</token><token pos="np0000l">Andreu</token><token pos="np0000l">Mas-Colell</token><token pos="fc">,</token><token pos="sps00">con</token><token pos="da0fs0">la</token><token pos="ncfs000">mirada</token><token pos="aq0fsp">puesta</token><token pos="sps00">en</token><token pos="da0mp0">los</token><token pos="ncmp000">dividendos</token>
		</rheme>
		<semantic_roles>
			<main_frame type="Defending" head="defender"></main_frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 Un grupo de rectores cuenta en privado que el secretario de Estado de Universidades, Julio Iglesias de Ussel, ha llegado a afirmar que "si en la sociedad española el PP tiene el 50% de los votos, también le corresponden el 50% de los rectores", lo que lleva a UGT y CCOO a definir la LOU como "ley de partido".
		</str>
		<theme>
			<token pos="da0ms0">el</token><token pos="ncms000">secretario</token><token pos="sps00">de</token><token pos="np00000">Estado</token><token pos="sps00">de</token><token pos="np00000">Universidades</token><token pos="fc">,</token><token pos="ncms000">Julio</token><token pos="ncms000">Iglesias</token><token pos="sps00">de</token><token pos="ncms000">Ussel</token><token pos="fc">,</token>
		</theme>
		<rheme>
			<token pos="vaip3s0">ha</token><token pos="vmp00sm">llegado</token><token pos="sps00">a</token><token pos="vmn0000">afirmar</token><token pos="vmip3s0">tiene</token><token pos="vmip3p0">corresponden</token>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="Un grupo de rectores "></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 Hoy no hay correlato entre la mayoría absoluta del partido del Gobierno y el poder que detenta en las universidades.
		</str>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 No hay precedentes de este sistema en ninguna universidad del mundo.
		</str>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 En la de San Carlos, de Guatemala, trató de ponerse en práctica, pero la idea se desechó.
		</str>
		<theme>
			<token pos="da0fs0">la</token><token pos="ncfs000">idea</token>
		</theme>
		<rheme>
			<token pos="p0000000">se</token><token pos="vmis3s0">desechó</token>
		</rheme>
		<semantic_roles>
			<frame type="Awareness" head="idea">
				<argument type="Cognizer" dependent="pero la"/>
				<argument type="Content" dependent="se"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 Sólo en la Universidad de Chapingo, en México, se elige el rector por sufragio universal, pero allí la máxima es un hombre un voto.
		</str>
		<theme>
			<token pos="da0fs0">la</token><token pos="ncfs000">máxima</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="di0ms0">un</token><token pos="ncms000">hombre</token><token pos="di0ms0">un</token><token pos="ncms000">voto</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 O sea: la opción del catedrático vale lo mismo que la del estudiante.
		</str>
		<theme>
			<token pos="da0fs0">la</token><token pos="ncfs000">opción</token><token pos="spcms">del</token><token pos="ncms000">catedrático</token>
		</theme>
		<rheme>
			<token pos="vmip3s0">vale</token><token pos="da0ns0">lo</token><token pos="pi0ms000">mismo</token><token pos="cs">que</token><token pos="da0fs0">la</token><token pos="spcms">del</token><token pos="nccs000">estudiante</token>
		</rheme>
		<semantic_roles>
			<frame type="Natural_features" head="sea">
				<argument type="Name" dependent="O"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 El principal reproche que se hace al nuevo sistema es que las elecciones a rector se asemejaran a los comicios políticos como dos gotas de agua.
		</str>
		<theme>
			<token pos="da0ms0">El</token><token pos="aq0cs0">principal</token><token pos="ncms000">reproche</token><token pos="pr0cn000">que</token><token pos="p0000000">se</token><token pos="vmip3s0">hace</token><token pos="spcms">al</token><token pos="aq0ms0">nuevo</token><token pos="ncms000">sistema</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="cs">que</token><token pos="da0fp0">las</token><token pos="ncfp000">elecciones</token><token pos="sps00">a</token><token pos="ncms000">rector</token><token pos="p0300000">se</token><token pos="vmsi3p0">asemejaran</token><token pos="sps00">a</token><token pos="da0mp0">los</token><token pos="ncmp000">comicios</token><token pos="aq0mp0">políticos</token><token pos="cs">como</token><token pos="dn0cp0">dos</token><token pos="ncfp000">gotas</token><token pos="sps00">de</token><token pos="ncfs000">agua</token>
		</rheme>
		<semantic_roles>
			<frame type="Intentionally_act" head="dos">
				<argument type="Act" dependent="dos gotas de agua"/></frame>
			<frame type="Leadership" head="principal">
				<argument type="Governed" dependent="al"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 Las campañas exigirán una infraestructura y una financiación que están fuera del alcance del común de los catedráticos que aspiran a la plaza.
		</str>
		<theme>
			<token pos="da0fp0">Las</token><token pos="ncfp000">campañas</token>
		</theme>
		<rheme>
			<token pos="vmif3p0">exigirán</token><token pos="di0fs0">una</token><token pos="ncfs000">infraestructura</token><token pos="cc">y</token><token pos="di0fs0">una</token><token pos="ncfs000">financiación</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 ¿Quién se la proporcionará?
		</str>
		<theme>
			<token pos="pt0cs000">Quién</token>
		</theme>
		<rheme>
			<token pos="pp3cn000">se</token><token pos="pp3fsa00">la</token><token pos="vmif3s0">proporcionará</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 "Los partidos, porque ahí veremos enfrentados al candidato de tal formación con la otra y los votantes se guiarán por sus preferencias políticas", opina un ex rector de una universidad catalana.
		</str>
		<theme>
			<token pos="da0mp0">los</token><token pos="nccp000">votantes</token>
		</theme>
		<rheme>
			<token pos="p0300000">se</token><token pos="vmif3p0">guiarán</token><token pos="sps00">por</token><token pos="dp3cp0">sus</token><token pos="ncfp000">preferencias</token><token pos="aq0fp0">políticas</token>
		</rheme>
		<semantic_roles>
			<frame type="Modality_Reporter" head="un ex rector de una universidad catalana "></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<str>
			 El de la Universidad Complutense de Madrid, Rafael Puyol, nada sospechoso de hallarse en la órbita socialista, teme que "el procedimiento no sólo va a favorecer las injerencias externas, sino que reducirá la capacidad del elegido por la enorme dispersión del voto".
		</str>
		<theme>
			<token pos="da0ms0">el</token><token pos="ncms000">procedimiento</token>
		</theme>
		<rheme>
			<token pos="fe">quot;</token><token pos="rn">no</token><token pos="rg">sólo</token><token pos="vmip3s0">va</token><token pos="sps00">a</token><token pos="vmn0000">favorecer</token><token pos="da0fp0">las</token><token pos="ncfp000">injerencias</token><token pos="aq0fp0">externas</token><token pos="fc">,</token><token pos="pi0cs000">que</token><token pos="vmif3s0">reducirá</token><token pos="da0fs0">la</token><token pos="ncfs000">capacidad</token><token pos="spcms">del</token><token pos="aq0msp">elegido</token><token pos="sps00">por</token><token pos="da0fs0">la</token><token pos="aq0cs0">enorme</token><token pos="ncfs000">dispersión</token><token pos="spcms">del</token><token pos="ncms000">voto</token><token pos="fe">quot;</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


</text>